### ISSUE TITLE
flyflix.py error

### ISSUE THREAD

**Issue by rjs360** [floesche/FlyFlix#12]
Hi there, 
did (aspects of) flyflix receive an update very recently?  I installed and successfully ran the flyflix.py script two days ago, but now it throws this error:

$ python3 flyflix.py
Traceback (most recent call last):
  File "/home/rjs/FlyFlix/flyflix.py", line 19, in <module>
    from flask_socketio import SocketIO
  File "/home/rjs/.local/lib/python3.10/site-packages/flask_socketio/__init__.py", line 24, in <module>
    from werkzeug._reloader import run_with_reloader
  File "/home/rjs/.local/lib/python3.10/site-packages/werkzeug/_reloader.py", line 391, in <module>
    __import__("watchdog.observers")
  File "/home/rjs/.local/lib/python3.10/site-packages/watchdog/observers/__init__.py", line 63, in <module>
    from .inotify import InotifyObserver as Observer
  File "/home/rjs/.local/lib/python3.10/site-packages/watchdog/observers/inotify.py", line 76, in <module>
    from watchdog.observers.api import (
  File "/home/rjs/.local/lib/python3.10/site-packages/watchdog/observers/api.py", line 23, in <module>
    from watchdog.utils.bricks import SkipRepeatsQueue
  File "/home/rjs/.local/lib/python3.10/site-packages/watchdog/utils/bricks.py", line 175, in <module>
    class OrderedSet(collections.MutableSet):
AttributeError: module 'collections' has no attribute 'MutableSet'

I looked around a bit and found a "similar" issue for another software here:
https://github.com/Bogdanp/dramatiq/issues/428

But I am not sure how to go about trying their solution.

Perhaps it is a python issue?
My python version is 3.10.6
Any ideas?
-Ruud

**Comment by rjs360** [comment]
This seemed to be related to installing flyhaviour (even through a virtual environment) on the same machine. Fixed this by reinstalling ubuntu OS and fictrac+flyflix, and running flyhaviour on a separate machine instead.
